2023.04.14 Book:archive 관리자 기능 구현 1. 상품 관리 기능 구현 (상품 정보 등록, 상품 정보 수정)
2. 주문 관리 기능 구현 (상품의 배송 상태 설정)

3. 회원 관리 기능 구현 (회원 정보 조회)
(1)SEVERE: 경로 [/bookarchive]의 컨텍스트 내의 서블릿 [appServlet]을(를) 위한 Servlet.service() 호출이, 근본 원인(root cause)과 함께, 예외 [Request processing failed;
nested exception is org.springframework.jdbc.UncategorizedSQLException: Error setting null for parameter #3 with JdbcType OTHER .
Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property.
Cause: java.sql.SQLException: 부적합한 열 유형: 1111
; uncategorized SQLException for SQL []; SQL state [99999]; error code [17004]; 부적합한 열 유형: 1111;
nested exception is java.sql.SQLException: 부적합한 열 유형: 1111]을(를) 발생시켰습니다.
java.sql.SQLException: 부적합한 열 유형: 1111
<해결> form에서 넘긴 데이터의 VO 변수가 바인드 된다고해도 사용하는 변수가 null값으로 세팅되면 발생
=> mybatis-context.xml 에서  bean의 property 네임이 "configLocation"인 xml (book:archive project에서는 modelsConfig.xml) 찾아서 세팅 추가
<settings>
        <setting name="cacheEnabled" value="false" />
        <setting name="jdbcTypeForNull" value="NULL" />
    </settings>
** 주의 !! typealias 밑에 setting 넣었더니 오류 발생 (해결)
configuration의 요소 정의 순서 확인하기 ( The content of element type "configuration" must match "(properties?,settings?,typeAliases?,typeHandlers?,objectFactory?,objectWrapperFactory?,reflectorFactory?,plugins?,environments?,databaseIdProvider?,mappers?)". )
<configuration>
properties
settings
typeAliases
typeHandlers
objectFactory
objectWrapperFactory
reflectorFactory
plugins
environments
databaseIdProvider
mappers
</configuration>

(2) [ORACLE] 오라클 ORA-00942: 테이블 또는 뷰가 존재하지 않습니다.
=> 해결 중..
* 회원 관리 메인 페이지 구현 후 member_list 불러오는 과정에서 오류 발생

4. 회원 기능 : 주문, 장바구니, 제품 상세조회 페이지 내에서 가격 및 할인율이 제대로 적용되지 않는 에러 발견 !
<해결> mycartList.jsp에서 ${item.goods_price*0.9 }가  ${item.goods_sales_price*0.9 }로 적용되어 할인이 여러번 적용되는 에러 확인
내용 고쳐서 에러 해결 + DB에서 받아오는 적립금과 가격도 전체적으로 맞춰서 수정해서 에러 해결 !!

*** 세션 [9A539FBD78B85DE541626CEE674543A7]을(를) 위한 세션 속성 [quickGoodsList]을(를) 직렬화할 수 없습니다.
java.io.NotSerializableException: com.myspring.bookarchive.goods.vo.GoodsVO
// 프로젝트 톰캣 종료하면 나오는 에러 (서버 클린으로 해결했지만, 간혹 발생해서 이유 검색 후 아카이빙)

(에러명) java.io.NotSerializableException:Cannot serialize session attribute

세션값을 가지는 Bean클래스가 implements Serializable을 하지 않았기 때문에 생기는 예외,
세션값을 받는 빈 클래스는 반드시 직렬화해야 네트워크상에서 안전함

1 )  class A implements Serializable
Serializable 구현 누락되어 발생한다.
객체를 통신 및 저장 하기 위해선 반드시 Serializable 를 구현 해야한다.
2 ) java.io.NotSerializableException: #{패키지.클래스}
#{패키지.클래스}가 직렬화 시킨 클래스 안에 들어가있는지 확인 해봐야한다.
위 클래스에 Serializable 을 구현 하거나, 불필요한 클래스라면 빼주면 해결된다.

**자바 직렬화(Java Serialization) : 객체에 저장된 데이터를 스트림에 쓰기 위해 연속적인 데이터로 변환하는 것
역직렬화(deserialization) : 스트림에서 데이터를 읽어 객체로 변환하는 것
객체를 파일에 저장하거나 파일에서 꺼내오기 위해서 또는 객체를 네트워크를 통해 전송하기 위해서는 미리 객체를 직렬화해야한다