2023.04.13 book:archive_final **기존 bookarchive 프로젝트에서 인코딩 이슈로 새로운 프로젝트 생성해서 인코딩 문제 해결함
1. 메인페이지 구현
(1) WARN : org.springframework.web.context.support.XmlWebApplicationContext -
Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'goodsDAO':
Injection of autowired dependencies failed;
nested exception is org.springframework.beans.factory.BeanCreationException:
Could not autowire field:
private org.apache.ibatis.session.SqlSession com.myspring.bookarchive.goods.dao.GoodsDAOImpl.sqlSession;
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException:
No qualifying bean of type [org.apache.ibatis.session.SqlSession] found for dependency:
expected at least 1 bean which qualifies as autowire candidate for this dependency.
Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
<해결>web.xml 수정해서 해결 (param-value 위치 변경)
 <context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>/WEB-INF/spring/mybatis-context.xml</param-value>
 </context-param>

** 프로젝트를 진행하면서 sqlSession 관련 오류를 많이 만남
(1-1) 프로젝트 pom.xml 의존성 제대로 추가되어 있는지 확인 (maven dependencies도 확인)
- Spring JDBC, Mybatis, Mybatis Spring
(1-2) Mybatis Mapper 파일 확인 (오탈자, 혹은 DB, DAO 다르게 설정된 부분있는지)
(1-3) modelsConfig.xml 파일에 <typeAliases> 확인하기 (빠진 부분 있는지, 오탈자 있는지)
(1-4) 스프링 설정파일(applicationContext.xml)에 SqlSessionFactory 등록되어 있는지 확인하기 (DB 연동)
(bookarchive 프로젝트는 mybatis-context.xml 에 등록되어 있음)
 <bean id="sqlSession"
  class="org.mybatis.spring.SqlSessionTemplate">
  <constructor-arg ref="sqlSessionFactory"></constructor-arg>
 </bean>
(1-5)DAO 관련 클래스가 상속 구현 잘 되어 있는지 확인하기
(1-6) SqlSession / sqlSession << 대소문자 확인하기

(2) 인코딩 이슈 재발 방지
web.xml 에 filter 관련 코드 추가
 <filter>
  <filter-name>encodingFilter</filter-name>
  <filter-class>
   org.springframework.web.filter.CharacterEncodingFilter
  </filter-class>
  <init-param>
   <param-name>encoding</param-name>
   <param-value>UTF-8</param-value>
  </init-param>
 </filter>
 <filter-mapping>
  <filter-name>encodingFilter</filter-name>
  <url-pattern>/*</url-pattern>
 </filter-mapping>

2. 상품 상세 구현하기

3. Ajax 이용해 검색 자동 완성 기능 구현하기

4. 로그인 / 로그아웃 기능 구현

5. 회원가입 기능 구현 (인코딩 이슈 해결 !!!!!)
(1) SEVERE: 경로 [/bookarchive]의 컨텍스트 내의 서블릿 [appServlet]을(를) 위한 Servlet.service() 호출이, 근본 원인(root cause)과 함께, 예외 [Request processing failed; nested exception is java.lang.NullPointerException]을(를) 발생시켰습니다.
java.lang.NullPointerException
<해결> Query에 null 값이 들어갔을 경우 발생
(1-1) Controller, DAO, Service 단에서 각각에 넘겨주는 쿼리값 주입 확인
(1-2) DB가 run 중인지 확인

6. 장바구니 기능 구현하기 (상품 장바구니에 추가, 장바구니 목록보기)
(1) WARNING: 세션 [08237EB1C8939E93498DD0A50BEC9CF2]을(를) 위한 세션 속성 [cartMap]을(를) 역직렬화할 수 없습니다.
4월 13, 2023 3:23:29 오후 org.apache.catalina.session.StandardManager startInternal
SEVERE: 세션 저장소로부터 세션들을 로드하는 중 예외 발생
java.io.StreamCorruptedException: invalid type code: 00
(1-1) 프로젝트 클린, 서버 클린 후 서버 재실행 <해결 !!!>
(1-2) 윈도우즈 서비스로 등록한 톰캣의 "catalina.시작일자.log" 확인해서 ~CATALINA/work/Vatalina/localhost 디렉토리에 위치한 모든 정보 삭제 후
서비스 재시작 (정보는 다시 빌드된다)

7. (새로운 기능 추가) 메인화면에서 책 장바구니 담을 때 (로그인 안 했을 시) >> 로그인 먼저 하라고 팝업 뜨고 로그인 페이지로 넘어가는 기능 구현
: order기능 참고해서 Controller와 jsp (function)으로 구현해봤지만 실패,, => Ajax error 알림을 활용해서 url로 넘어가도록 코드 작성해 기능 구현 완료 !!!
post 방식으로 보내주고 나서 컨트롤러에서 redirect 로 페이지를 변경해주고 싶었지만 작동을 하지 않아서
바로 로그인폼으로 가고 싶어서 location.replace() 함수를 이용했음.
error : function(data, textStatus) {
    if(data == "[object Object]"){
     alert("로그인 후 장바구니에 담을 수 있습니다!");
     let url = "${contextPath}/member/loginForm.do";
     console.log(url);
     location.replace(url);
    }

8. 주문 기능 구현 (상품 상세 페이지에서 주문, 장바구니 상품 주문)

9.마이페이지 기능 구현 (마이페이지 메인 화면 구현, 회원 정보 상세 페이지 구현, 개인정보 수정 기능 구현)

10. CSS기능 붙여서 폰트와 페이지 내 background color 변경
(1) 폰트 변경
: 폰트 페이지에서 복사한 코드를 적용하고자 하는 페이지 css 에 붙여넣기
(2) CSS 적용이 안되는 경우
(2-1) 캐시 문제 : 브라우저 캐시 삭제 후 F5 새로고침 <이걸로 해결 !!>
(2-2) 전에 쓰였던 CSS와 충돌
: 적용됐으면 하는 CSS 속성값 뒤에 !important 붙여서 우선 적용되도록 할 수 있음

** Loading xml bean definitions from class path resource  오류
: SQL 문법 구조 오류로 나타나는데 Mapper 내의 오타 확인 필요함,, (대소문자도 당연히 맞춰줘야함!)
: mapper 파일에서는 #{ } 으로 사용해야함 ${}으로 쓴 건 아닌지 확인해보기

**org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
: 어노테이션 정확히 설정되어있는지 확인하기 (자바파일 내에도 @Service와 @Autowired 제대로 설정되어 있는지 꼭꼭꼭 확인해보기)
: <context:component-scan base-package="패키지명" /> 패키지명 확인해보기
: Service단 어노테이션 다시 한 번 확인해보고 ServiceImpl도 확인 후 @Repository 어노테이션을 추가
:  mapper 파일 내의 오탈자 확인해보기

** Initialization of bean failed 에러
: lib 충돌 문제일 수 있기 때문에 pom.xml 확인 후 ibatis dependency 삭제 후 다시 입력해보기 (해결)

** Multiple annotations found at this line 에러
: namespace 확인해서 오류 해결
applicaitonContext.xml -> namespaces 클릭 -> Configure Namespaces에 context 체크 확인 -> context의 Namespaces 버전확인